### ISSUE TITLE
[BUG]: Error: Rendered more hooks than during the previous render.

### ISSUE THREAD

**Issue by mvoemel** [mvoemel/studyflow#118]
# Describe the bug
<img width="230" alt="image" src="https://github.com/user-attachments/assets/d9711a05-481d-4df3-84db-8faec5d96534">
<img width="1020" alt="image" src="https://github.com/user-attachments/assets/581bda70-3cc5-46d1-8eeb-760b0e5ca74a">

# To Reproduce
1. Register
2. Login
3. Go to /degree/:id
4. Go to /dashboard
5. Create Degree
6. Select Degree
7. Go to /degree/:id

# Expected behavior
The current selected degree should be filled out in the form.

# (Maybe) Possible solution
<img width="683" alt="image" src="https://github.com/user-attachments/assets/79b3bc42-725c-4069-8533-90d501927f47">

**Comment by mvoemel** [comment]
Also updating current degree is not possible:
<img width="378" alt="image" src="https://github.com/user-attachments/assets/b7e51519-7441-410c-b857-d059069e4853">

This is probably the reason it does not work.

The id -1 which represents not existing should not be returned by the endpoints rather it just should be undefined.

**Comment by ShpetimV** [comment]
> Also updating current degree is not possible: <img alt="image" width="378" src="https://private-user-images.githubusercontent.com/79416152/393371130-b7e51519-7441-410c-b857-d059069e4853.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NzE2MjIsIm5iZiI6MTczMzU3MTMyMiwicGF0aCI6Ii83OTQxNjE1Mi8zOTMzNzExMzAtYjdlNTE1MTktNzQ0MS00MTBjLWI4NTctZDA1OTA2OWU0ODUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDExMzUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhYzk1OWY0ZjU0MzkwNTQ0MjRmODU2ZDI5NzY5ZTU0YzE2Njk3MDUxOTYzN2Q3ZWMxMjQ5ZjBlZWIzOTBjY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CoQVS9XktEnHvS0aI5YUCuds4yTvwMp4j5QzvYw2eNc">
> 
> This is probably the reason it does not work.
> 
> The id -1 which represents not existing should not be returned by the endpoints rather it just should be undefined.

Either way if you return "-1" or "null" from the backend you will have to handle it in the frontend accordingly. Because java cannnot return an "undefined. It can either return a null or -1 but if you want to parse it into an undefined you will have to do that manually in the frontend.
