### ISSUE TITLE
[Feature]: Implement ModuleController and Module

### ISSUE THREAD

**Issue by ShpetimV** [mvoemel/studyflow#57]
#### Description
Implement a `Module` class and a `ModuleController` class to manage modules for each semester. The `ModuleController` should provide endpoints to create, read, update, and delete modules.

#### Endpoints

1. **Create Module**
   - **Path:** `/module`
   - **Method:** `POST`
   - **Description:** Create a new module.
   - **Request Body:** JSON object containing module details (e.g., name, description, semester).
   - **Response:** HTTP 201 Created with the created module details.

2. **Get Module by ID**
   - **Path:** `/module/{id}`
   - **Method:** `GET`
   - **Description:** Retrieve a module by its ID.
   - **Response:** HTTP 200 OK with the module details.

3. **Get All Modules**
   - **Path:** `/modules`
   - **Method:** `GET`
   - **Description:** Retrieve all modules.
   - **Response:** HTTP 200 OK with a list of all modules.

4. **Update Module**
   - **Path:** `/module/{id}`
   - **Method:** `PUT`
   - **Description:** Update an existing module by its ID.
   - **Request Body:** JSON object containing updated module details.
   - **Response:** HTTP 200 OK with the updated module details.

5. **Delete Module**
   - **Path:** `/module/{id}`
   - **Method:** `DELETE`
   - **Description:** Delete a module by its ID.
   - **Response:** HTTP 204 No Content.

**Comment by mormeli** [comment]
Closed with the merge of  #77.
